[project]
name = "sparse-ir-tutorial"
version = "0.1.0"
dependencies = [
    "jupyter-book<2.0",
    "jupytext",
    "matplotlib",
    "ghp-import",
    "jupyterlab",
    "sparse-ir>=2.0.0a9",
    "admmsolver",
    "pylibsparseir>=0.7.5",
]
